/* eslint-disable no-console */

import { env } from "@/env.mjs"

export enum LogLevel {
  Error = "error",
  Warn = "warn",
  Info = "info",
  Debug = "debug",
  Default = "log",
}

const LogLevels: Record<LogLevel, Record<string, string>> = {
  [LogLevel.Error]: {
    title: "🚨",
    background: "#ef4444",
  },
  [LogLevel.Warn]: {
    title: "🔔",
    background: "#fb923c",
  },
  [LogLevel.Info]: {
    title: "👀",
    background: "#10b981",
  },
  [LogLevel.Debug]: {
    title: "🔎",
    background: "#0ea5e9",
  },
  [LogLevel.Default]: {
    title: "🪵",
    background: "#f472b6",
  },
}

interface LoggerConfig {
  breakpoint?: string
  level?: LogLevel
  unstyled?: boolean
}

/**
 * @title Debug Logger
 * @description Apply console logger exclusively in development environment
 * @param breakpointComment - Autogenerated with `lg` snippet
 */
export const logger = (
  { breakpoint, level = LogLevel.Info, unstyled = false }: LoggerConfig,
  ...messages: unknown[]
): void => {
  const isVisible: boolean = env.NEXT_PUBLIC_SHOW_LOGGER === "1" || false
  if (!isVisible) return

  let messageIndex = 0

  // Check if the first parameter is a log level
  if (
    typeof messages[0] === "string" &&
    Object.values(LogLevel).includes(messages[0] as LogLevel)
  ) {
    level = messages[0] as LogLevel
    messageIndex = 1
  }

  const logLevel = LogLevels[level]

  const css = `
    color: #ffffff;
    background-color: ${logLevel.background ?? "#000000"};
    font-weight: bold;
    padding: 3px;
  `
  const styles: string[] = unstyled
    ? []
    : [css, `${css}; font-weight: bold;`, `${css}; font-weight: normal;`]

  const parts = [
    "%c",
    `${logLevel.title || ""}${level.toUpperCase()}`,
    `%c${breakpoint ?? ""}%c`,
  ]

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const args: any[] = [...styles, ...messages.slice(messageIndex)]

  console[level].apply(null, [parts.join(" ")].concat(args))
}
